### ISSUE TITLE
setting up

### ISSUE THREAD

**Issue by jmoney24244** [quantumcored/paradoxiaRAT#11]
sudo python3 paradoxia.py

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b5_9q3p0/instagram-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b5_9q3p0/instagram-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b9wo3xi4
         cwd: /tmp/pip-install-b5_9q3p0/instagram-py/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b5_9q3p0/instagram-py/setup.py", line 13, in <module>
        from InstagramPy import __version__
      File "/tmp/pip-install-b5_9q3p0/instagram-py/InstagramPy/__init__.py", line 11, in <module>
        from .InstagramPySession import InstagramPySession, DEFAULT_PATH
      File "/tmp/pip-install-b5_9q3p0/instagram-py/InstagramPy/InstagramPySession.py", line 12, in <module>
        from stem import Signal
    ModuleNotFoundError: No module named 'stem'

**Comment by quantumcore** [comment]
Delete and reclone, You seem to have an old version.
