### ISSUE TITLE
Error - function TCPServer

### ISSUE THREAD

**Issue by etaylor77** [quantumcored/paradoxiaRAT#8]
The remote agents are checking in, but there are a bunch of errors when it happens.

Image follows this snippet:

`paradoxia >> [+] Getting information..
Unhandled exception in thread started by <function TCPServer at 0x7f42da241a60>
Traceback (most recent call last):
  File "/home/azureuser/paradoxiaRAT/kernel/main.py", line 806, in TCPServer
    notify("Paradoxia", "New Connection : " + cld.returnClientName())
  File "/home/azureuser/paradoxiaRAT/kernel/other.py", line 96, in notify
    message
  File "/usr/local/lib/python3.6/dist-packages/plyer/facades/notification.py", line 82, in notify
    timeout=timeout, ticker=ticker, toast=toast
  File "/usr/local/lib/python3.6/dist-packages/plyer/platforms/linux/notification.py", line 43, in _notify
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
`
![image](https://user-images.githubusercontent.com/12686164/98998477-2ffae200-2504-11eb-8e54-754af138524a.png)

**Comment by quantumcore** [comment]
There seems to be no problem with the server as the title says. This error is from python module plyer trying to send you desktop toast notifications. You should be able to use the rest of the program normally. I will be fixing this issue soon.

**Comment by quantumcore** [comment]
By the way I think you didn't notice but you accidentally posted your public Ip.

**Comment by quantumcore** [comment]
Closed because no response from op.
